kind: MariaDB
apiVersion: k8s.mariadb.com/v1alpha1
metadata:
  name: mariadb
spec:
  rootPasswordSecretKeyRef:
    generate: false
    name: mariadb-password
    key: DB_PASSWORD
  metrics:
    passwordSecretKeyRef:
      generate: false
      name: mariadb-metrics
      key: DB_PASSWORD
    enabled: true
  storage:
    size: 1Gi
  passwordSecretKeyRef:
    generate: false
    name: mariadb-password
    key: DB_PASSWORD
  database: grr
  username: grr_user
